GODS = {
"Achilles" : "warrior",
"Agni" : "mage",
"Ah Muzen Cab" : "hunter",
"Ah Puch" : "mage",
"Amaterasu" : "warrior",
"Anhur" : "hunter",
"Anubis" : "mage",
"Ao Kuang" : "mage",
"Aphrodite" : "mage",
"Apollo" : "hunter",
"Arachne" : "assassin",
"Ares" : "guardian",
"Artemis" : "hunter",
"Artio" : "guardian",
"Athena" : "guardian",
"Awilix" : "assassin",
"Baba Yaga" : "mage",
"Bacchus" : "guardian",
"Bakasura" : "assassin",
"Baron Samedi" : "mage",
"Bastet" : "assassin",
"Bellona" : "warrior",
"Cabrakan" : "guardian",
"Camazotz" : "assassin",
"Cerberus" : "guardian",
"Cernunnos" : "hunter",
"Chaac" : "warrior",
"Chang'e" : "mage",
"Charybdis" : "hunter",
"Chernobog" : "hunter",
"Chiron" : "hunter",
"Chronos" : "mage",
"Cliodhna" : "assassin",
"Cthulu" : "guardian",
"Cu Chulainn" : "warrior",
"Cupid" : "hunter",
"Da Ji" : "assassin",
"Danzaburou" : "hunter",
"Discordia" : "mage",
"Erlang Shen" : "warrior",
"Eset" : "mage",
"Fafnir" : "guardian",
"Fenrir" : "assassin",
"Freya" : "mage",
"Ganesha" : "guardian",
"Geb" : "guardian",
"Gilgamesh" : "warrior",
"Guan Yu" : "warrior",
"Hachiman" : "hunter",
"He Bo" : "mage",
"Heimdallr" : "hunter",
"Hel" : "mage",
"Hera" : "mage",
"Hercules" : "warrior",
"Horus" : "warrior",
"Hou Yi" : "hunter",
"Hun Batz" : "assassin",
"Izanami" : "hunter",
"Janus" : "mage",
"Jing Wei" : "hunter",
"Jormungandr" : "guardian",
"Kali" : "assassin",
"Khepri" : "guardian",
"King Arthur" : "warrior",
"Kukulkan" : "mage",
"Kumbhakharna" : "guardian",
"Kuzenbo" : "guardian",
"Loki" : "assassin",
"Medusa" : "hunter",
"Mercury" : "assassin",
"Merlin" : "mage",
"Morgan Le Fay" : "mage",
"Mulan" : "warrior",
"Ne Zha" : "assassin",
"Neith" : "hunter",
"Nemesis" : "assassin",
"Nike" : "warrior",
"Nox" : "mage",
"Nu Wa" : "mage",
"Odin" : "warrior",
"Olorun" : "mage",
"Osiris" : "warrior",
"Pele" : "assassin",
"Persephone" : "mage",
"Poseidon" : "mage",
"Ra" : "mage",
"Raijin" : "mage",
"Rama" : "hunter",
"Ratatoskr" : "assassin",
"Ravana" : "assassin",
"Scylla" : "mage",
"Serqet" : "assassin",
"Set" : "assassin",
"Skadi" : "hunter",
"Sobek" : "guardian",
"Sol" : "mage",
"Sun Wukong" : "warrior",
"Susano" : "assassin",
"Sylvanus" : "guardian",
"Terra" : "guardian",
"Thanatos" : "assassin",
"The Morrigan" : "mage",
"Thor" : "assassin",
"Thoth" : "mage",
"Tiamat" : "mage",
"Tsukuyomi" : "assassin",
"Tyr" : "warrior",
"Ullr" : "hunter",
"Vamana" : "warrior",
"Vulcan" : "mage",
"Xbalanque" : "hunter",
"Xing Tian" : "guardian",
"Yemoja" : "guardian",
"Ymir" : "guardian",
"Zeus" : "mage",
"Zhong Kui" : "mage",
}